sudo: false

cache:
    directories:
        - $HOME/.ccache
        - /usr/local

git:
    submodules: false

script:
    - brew install ccache
    - echo 'int main() { return 0; }' > main.c
    - ccache gcc main.c -c test.o
    - ccache -s
