language: objective-c

cache:
    directories:
        - $HOME/.ccache
        - /usr/local

git:
    submodules: false

script:
    - brew install doxygen nasm yasm optipng imagemagick coreutils intltool ninja antlr ccache
