sudo: false

language: objective-c

git:
    #may be useful if new commits has been pushed in the mean time
    depth: 5
    submodules: false

cache:
    directories:
        - $HOME/.ccache
        - /usr/local


script:
    - brew install doxygen
# env:
#     global:
#         - secure: "JPPcWdmNIJiR3YcIwe0LRYce6qDdsiagO+eKKAp7eVk/wD9UHbz96Ms2FFkXxPhRJB1PA6Pf8FpAzIL2YRiJL9jRtKHSvtdF1cSto+57XyBkCsw7PkMVUIxp7fg6Wiwn3H3tucF8jisIkv/Pn7R+9EqePkZSqqu3+ig5AX9ApQ4="
#         - KIF_SCREENSHOTS=$PWD/Screens

# before_install:
#     - brew update 1>/dev/null
#     - brew install doxygen nasm yasm optipng imagemagick coreutils intltool ninja antlr ccache
#     - brew upgrade cmake
#     - wget --no-check-certificate https://raw.githubusercontent.com/FFmpeg/gas-preprocessor/master/gas-preprocessor.pl
#     - chmod +x gas-preprocessor.pl
#     - mv gas-preprocessor.pl /usr/local/bin
#     - ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize
#     - ln -s /usr/bin/strings /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/strings
#     - git submodule update --init --recursive

# install:
#     - ccache -s
#     - ./prepare.py -d x86_64 -G Ninja -DCMAKE_C_COMPILER_LAUNCHER=$(which ccache) -DCMAKE_CXX_COMPILER_LAUNCHER=$(which ccache)
#     - make -j4 -s 1>/dev/null
#     - ccache -s
#     - mkdir -p $KIF_SCREENSHOTS

# script:
#     # - xctool -project linphone.xcodeproj -scheme linphone -sdk iphonesimulator -destination name='iPhone 6' build 1>/dev/null
#     # - xctool -project linphone.xcodeproj -scheme linphone -sdk iphonesimulator -destination name='iPhone 6' test
#     - ccache -s

# after_script:
#     - ./Tools/imgur_upload.sh
